kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-deploy
  namespace: notes
  labels:
    app: node
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: asskit/notes:1bf42556c8a08266ae18560c67a857d4d05819c9
          ports:
            - name: web
              containerPort: 8080
