kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-deploy
  namespace: notes
  labels:
    app: node
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: asskit/notes:a0c2fa8dd344d9a6cfb5d90ae3526760a00c8840
          ports:
            - name: web
              containerPort: 8080
