kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-deploy
  namespace: notes
  labels:
    app: node
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: asskit/notes:fc903e4e7ecd02fdc082b65ffd629b57ec330705
          ports:
            - name: web
              containerPort: 8080
