kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-deploy
  namespace: notes
  labels:
    app: node
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: asskit/notes:c7065218d01e5061877ecb2fd17c54f408b390e4
          ports:
            - name: web
              containerPort: 8080
