name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - v4
  push:
    branches:
      - v4

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  dockerBuild-Push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:     
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
  
  dockerHubBuild-Push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:     
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/notes:${{ github.sha }}
          file: ./Dockerfile 
      
  edit-kube:
    needs: [ dockerBuild-Push, dockerHubBuild-Push ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:     
      - name: Checkout # checkout your sources file
        uses: actions/checkout@v3

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'kube/1-deployment.yaml'
          propertyPath: 'spec.template.spec.containers.0.image'
          value: '${{ secrets.DOCKER_USER }}/notes:${{ github.sha }}'
          commitChange: false
      
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ github.token }}
          commit_message: Image update to [ ${{ secrets.DOCKER_USER }}/notes:${{ github.sha }} ]

      - name: Refresh-Argocd
        run: curl 'https://argocd.nzdev.org/api/v1/applications/notes?refresh=normal&appNamespace=argocd'
